#!/usr/bin/env bash
#
# Docker and Compose plumbing.
#
# wait_healthy is the important one. `docker compose up -d` returns as soon as the
# container is *created*, not when the app inside is answering — so every deploy
# step in this repo follows it with a health wait, and every rollback decision is
# made on the result. Every image in this repo declares a HEALTHCHECK for that
# reason; a container without one reports "none" here and is treated as unknown
# rather than healthy.

[ -n "${_AMBER_INFRA_DOCKER:-}" ] && return 0
_AMBER_INFRA_DOCKER=1

# shellcheck source=install/lib/common.sh
. "$(dirname "${BASH_SOURCE[0]}")/common.sh"

ensure_docker() {
  if have docker && docker info >/dev/null 2>&1; then
    ok "docker present"
  else
    step "Installing Docker"
    run bash -c 'curl -fsSL https://get.docker.com | sh'
    run systemctl enable --now docker
    if dry; then ok "docker would be installed"; else ok "docker installed"; fi
  fi
  ensure_compose_plugin
}

ensure_compose_plugin() {
  if docker compose version >/dev/null 2>&1; then
    ok "docker compose plugin present"
    return 0
  fi
  step "Installing the docker compose plugin"
  run apt-get install -y docker-compose-plugin
  # A dry run skipped the install above, so asserting its result can only fail —
  # and a rehearsal that dies on the absence of something it deliberately did not
  # create is a false alarm, which is worse than no rehearsal at all. Same shape as
  # wait_healthy and wait_for_http, which return early for the same reason.
  if dry; then
    ok "docker compose plugin would be installed"
    return 0
  fi
  docker compose version >/dev/null 2>&1 || die "docker compose still unavailable after install"
}

compose() {  # compose DIR ARGS... — always -f the prod file, always from its dir
  local dir="$1"; shift
  local file
  # `|| true` is load-bearing: common.sh sets pipefail, so a glob that matches
  # nothing makes `ls` fail, fails the pipeline, and takes the whole script down at
  # the assignment — before the check below ever runs. rollback.sh already spells the
  # same idiom this way.
  # shellcheck disable=SC2012  # filenames here are generated by this repo:
  # timestamped and space-free. The find equivalent is correct and unreadable.
  file="$(ls "$dir"/docker-compose*.yml 2>/dev/null | head -n1 || true)"
  if [ -z "$file" ]; then
    # On a first install the compose file is put here by a `run install` a few lines
    # earlier — which a dry run skipped. Name the path it would have had and keep
    # printing, rather than aborting the rehearsal over a file the rehearsal itself
    # chose not to create. Outside a dry run this is still fatal, because then the
    # absence is real.
    if dry; then
      file="$dir/docker-compose.prod.yml"
    else
      die "no compose file in $dir"
    fi
  fi
  run docker compose -f "$file" --project-directory "$dir" "$@"
}

compose_up() {  # compose_up DIR
  local dir="$1"
  compose "$dir" pull
  compose "$dir" up -d
}

# `docker container inspect`, never bare `docker inspect`.
#
# Bare `inspect` is polymorphic: it resolves containers, images, networks and volumes
# from the same namespace. So on a box where the `caddy` IMAGE has been pulled but no
# container exists, `docker inspect caddy` SUCCEEDS, `.State` is absent, and this
# reports "none" — which every caller reads as "exists, just has no healthcheck".
# ensure_caddy then took its already-running branch and ran `docker exec caddy`, which
# failed with "No such container: caddy" and took the install down with it.
container_health() {  # container_health NAME -> healthy|unhealthy|starting|none|missing
  docker container inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' \
    "$1" 2>/dev/null || echo missing
}

container_state() {  # container_state NAME -> running|exited|created|paused|missing
  docker container inspect -f '{{.State.Status}}' "$1" 2>/dev/null || echo missing
}

wait_healthy() {  # wait_healthy NAME TIMEOUT_S
  local name="$1" timeout="${2:-90}" waited=0 status
  if dry; then
    echo "   ${c_yellow}dry-run${c_off} would wait for $name to become healthy"
    return 0
  fi
  while [ "$waited" -lt "$timeout" ]; do
    status="$(container_health "$name")"
    case "$status" in
      healthy) ok "$name is healthy"; return 0 ;;
      # A container with no HEALTHCHECK cannot be waited on meaningfully. Say so
      # rather than sleeping out the timeout and calling it a failure.
      none)    warn "$name declares no healthcheck — treating 'running' as good enough"
               [ "$(container_state "$name")" = "running" ] && return 0
               ;;
      missing) warn "$name does not exist as a container yet" ;;
    esac
    sleep 3
    waited=$((waited + 3))
  done
  warn "$name did not become healthy within ${timeout}s (last status: $(container_health "$name"))"
  return 1
}

image_of() {  # image_of COMPOSE_FILE -> the pinned image reference
  grep -E '^\s*image:' "$1" | head -n1 | sed -E 's/^\s*image:\s*//; s/\s*$//'
}
