#!/usr/bin/env bash
#
# Docker and Compose plumbing.
#
# wait_healthy is the important one. `docker compose up -d` returns as soon as the
# container is *created*, not when the app inside is answering — so every deploy
# step in this repo follows it with a health wait, and every rollback decision is
# made on the result. Every image in this repo declares a HEALTHCHECK for that
# reason; a container without one reports "none" here and is treated as unknown
# rather than healthy.

# shellcheck source-path=SCRIPTDIR
# ^ must appear before any COMMAND to be file-wide. Placed after one (the
#   double-source guard) it binds to the next statement only, and every source
#   after the first goes back to SC1091.

[ -n "${_AMBER_INFRA_DOCKER:-}" ] && return 0
_AMBER_INFRA_DOCKER=1

# shellcheck source=common.sh
. "$(dirname "${BASH_SOURCE[0]}")/common.sh"

ensure_docker() {
  if have docker && docker info >/dev/null 2>&1; then
    ok "docker present"
  else
    step "Installing Docker"
    run bash -c 'curl -fsSL https://get.docker.com | sh'
    run systemctl enable --now docker
    if dry; then ok "docker would be installed"; else ok "docker installed"; fi
  fi
  ensure_compose_plugin
}

ensure_compose_plugin() {
  if docker compose version >/dev/null 2>&1; then
    ok "docker compose plugin present"
    return 0
  fi
  step "Installing the docker compose plugin"
  run apt-get install -y docker-compose-plugin
  # A dry run skipped the install above, so asserting its result can only fail —
  # and a rehearsal that dies on the absence of something it deliberately did not
  # create is a false alarm, which is worse than no rehearsal at all. Same shape as
  # wait_healthy and wait_for_http, which return early for the same reason.
  if dry; then
    ok "docker compose plugin would be installed"
    return 0
  fi
  docker compose version >/dev/null 2>&1 || die "docker compose still unavailable after install"
}

# shellcheck disable=SC2012  # filenames here are generated by this repo:
# timestamped and space-free. The find equivalent is correct and unreadable.
compose() {  # compose DIR ARGS... — always -f the prod file, always from its dir
  local dir="$1"; shift
  local file
  # `|| true` is load-bearing: common.sh sets pipefail, so a glob that matches
  # nothing makes `ls` fail, fails the pipeline, and takes the whole script down at
  # the assignment — before the check below ever runs. rollback.sh already spells the
  # same idiom this way.
  file="$(ls "$dir"/docker-compose*.yml 2>/dev/null | head -n1 || true)"
  if [ -z "$file" ]; then
    # On a first install the compose file is put here by a `run install` a few lines
    # earlier — which a dry run skipped. Name the path it would have had and keep
    # printing, rather than aborting the rehearsal over a file the rehearsal itself
    # chose not to create. Outside a dry run this is still fatal, because then the
    # absence is real.
    if dry; then
      file="$dir/docker-compose.prod.yml"
    else
      die "no compose file in $dir"
    fi
  fi
  run docker compose -f "$file" --project-directory "$dir" "$@"
}

compose_up() {  # compose_up DIR
  local dir="$1"
  compose "$dir" pull
  compose "$dir" up -d
}

# `docker container inspect`, never bare `docker inspect`.
#
# Bare `inspect` is polymorphic: it resolves containers, images, networks and volumes
# from the same namespace. So on a box where the `caddy` IMAGE has been pulled but no
# container exists, `docker inspect caddy` SUCCEEDS, `.State` is absent, and this
# reports "none" — which every caller reads as "exists, just has no healthcheck".
# ensure_caddy then took its already-running branch and ran `docker exec caddy`, which
# failed with "No such container: caddy" and took the install down with it.
container_health() {  # container_health NAME -> healthy|unhealthy|starting|none|missing
  docker container inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' \
    "$1" 2>/dev/null || echo missing
}

container_state() {  # container_state NAME -> running|exited|created|paused|missing
  docker container inspect -f '{{.State.Status}}' "$1" 2>/dev/null || echo missing
}

# The tell for a crash loop. `unhealthy` and climbing is a process dying at boot;
# `unhealthy` and steady is a slow start or a probe that cannot reach it. The two
# want completely different next moves, and the status alone does not distinguish
# them.
container_restarts() {  # container_restarts NAME -> integer
  docker container inspect -f '{{.RestartCount}}' "$1" 2>/dev/null || echo 0
}

# HEARTBEAT_S: how often the wait below says what it is looking at. Low enough that
# nobody concludes the script is wedged, high enough not to bury the real output.
HEARTBEAT_S="${HEARTBEAT_S:-15}"

wait_healthy() {  # wait_healthy NAME TIMEOUT_S
  local name="$1" timeout="${2:-90}" waited=0 status restarts
  if dry; then
    echo "   ${c_yellow}dry-run${c_off} would wait for $name to become healthy"
    return 0
  fi
  # Progress, not silence. `starting` and `unhealthy` match no branch below, so this
  # loop used to print *nothing at all* for the full timeout — which made an ordinary
  # two-minute wait indistinguishable from a hung script, and got a real crash loop
  # read as "the updater wedged". Whoever is watching should never have to guess
  # whether anything is still happening.
  while [ "$waited" -lt "$timeout" ]; do
    status="$(container_health "$name")"
    case "$status" in
      healthy) ok "$name is healthy"; return 0 ;;
      # A container with no HEALTHCHECK cannot be waited on meaningfully. Say so
      # rather than sleeping out the timeout and calling it a failure.
      # `if` rather than `[ … ] && return 0`: as the last command of a case branch a
      # false test makes the whole `case` exit non-zero, which under `set -e` ends the
      # caller rather than this wait.
      none)    warn "$name declares no healthcheck — treating 'running' as good enough"
               if [ "$(container_state "$name")" = "running" ]; then return 0; fi
               ;;
      missing) warn "$name does not exist as a container yet" ;;
    esac
    sleep 3
    waited=$((waited + 3))
    if [ "$waited" -lt "$timeout" ] && [ "$((waited % HEARTBEAT_S))" -lt 3 ]; then
      restarts="$(container_restarts "$name")"
      echo "   ${c_blue}···${c_off} $name: ${status}, ${restarts} restart(s), ${waited}s of ${timeout}s"
    fi
  done
  warn "$name did not become healthy within ${timeout}s (last status: $(container_health "$name"))"
  # The logs, unprompted. Whoever is watching has just spent the whole timeout
  # learning nothing, and the answer is nearly always in the last few lines: a
  # missing key, an unwritable volume, a schema the process refuses to open. Making
  # them go and run `docker logs` themselves is a step that never had to exist.
  echo "   ${c_yellow}last 20 log lines from $name${c_off} (docker logs $name for the rest):"
  docker logs "$name" --tail 20 2>&1 | sed 's/^/   | /' || true
  return 1
}

image_of() {  # image_of COMPOSE_FILE -> the pinned image reference
  grep -E '^\s*image:' "$1" | head -n1 | sed -E 's/^\s*image:\s*//; s/\s*$//'
}
