#!/usr/bin/env bash
#
# Generate every placeholder the box is allowed to invent.
#
#   fill-secrets.sh                 every app, plus the sync-store's own keys
#   fill-secrets.sh --app bloom     just one
#   fill-secrets.sh --dry-run       say what would be generated, generate nothing
#
# The rule, and it is the whole file: **generated ⇒ the box; supplied ⇒ you; derived ⇒
# install.sh**. Nothing here invents an API key, because `install.sh`'s own principle
# is that a value invented at a prompt is a value that is not in the backup — and
# nothing here touches a key whose value exists somewhere else in the world.
#
# It replaces two `sed` loops in Aperture that decided what was generatable from the
# key's *name*: anything matching `*_KEYS` got 32 hex bytes. BLOOM_FERNET_KEYS ends in
# _KEYS, so it was offered, and the substitution left
# `<64 hex chars>-fernet-generate-key` — a value Bloom rejects at startup, produced by
# the button whose entire job was to save you the trouble. Branching on the manifest's
# declared `kind` instead of on the name is what makes that unrepresentable: a Fernet
# key is generated by the Fernet recipe because the app said so.
#
# Idempotent. A value that is not a placeholder is never touched, so this is safe to
# re-run and safe to run against a live box.
#
# shellcheck source-path=SCRIPTDIR

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/common.sh
. "$REPO_ROOT/install/lib/common.sh"
# shellcheck source=lib/secrets.sh
. "$REPO_ROOT/install/lib/secrets.sh"
# shellcheck source=lib/manifest.sh
. "$REPO_ROOT/install/lib/manifest.sh"

APP=""
while [ $# -gt 0 ]; do
  case "$1" in
    --app)      APP="$2"; shift 2 ;;
    --secrets)  SECRETS_FILE="$2"; shift 2 ;;
    --dry-run)  DRY_RUN=1; shift ;;
    -h|--help)  echo "usage: fill-secrets.sh [--app NAME] [--secrets FILE] [--dry-run]"; exit 1 ;;
    *) die "unknown argument: $1" ;;
  esac
done

secrets_check

GENERATED=0
NEEDS=""

#: 32 bytes of urlsafe base64, which is what `cryptography.fernet` accepts and what a
#: hex string is not. Built from openssl rather than Python so this has no dependency
#: on the app's own runtime being installed on the box.
gen_fernet() { openssl rand -base64 32 | tr '+/' '-_'; }

#: Replace the placeholder inside a compound `name:CHANGEME,name:CHANGEME` value,
#: giving each slot a DISTINCT token, and leaving the `name:` labels alone. Doing the
#: whole value at once is what would destroy the labels.
fill_compound() {  # fill_compound VALUE -> the value with each CHANGEME replaced
  local value="$1" out="" part
  local IFS=,
  for part in $value; do
    case "$part" in
      *CHANGEME*) part="${part%%CHANGEME*}$(gen_token)" ;;
    esac
    out="${out:+$out,}$part"
  done
  echo "$out"
}

fill_app() {  # fill_app APP
  local app="$1" key kind value new peer peer_key mine theirs
  manifest_have "$app" || { warn "no $app/manifest.yaml — skipping"; return 0; }
  step "Filling $app"

  while IFS= read -r key; do
    [ -z "$key" ] && continue
    value="$(yq -r ".apps.\"$app\".env.\"$key\" // \"\"" "$SECRETS_FILE")"
    [ "$value" = "null" ] && value=""
    case "$value" in *CHANGEME*) ;; *) continue ;; esac

    kind="$(manifest_kind "$app" "$key")"
    case "$kind" in
      generated:openssl-hex-32) new="$(gen_token)" ;;
      generated:fernet)         new="$(gen_fernet)" ;;
      generated:token)          new="$(fill_compound "$value")" ;;
      # Deliberately NOT generated here. A peer token is not this app's to invent —
      # it has to equal a value the *other* app holds, and minting a random one first
      # produces two apps that each believe they are configured and 401 each other.
      # pair_peers, below, runs once every app has been filled.
      peer_token) continue ;;
      supplied)
        NEEDS="$NEEDS
     $key — $(manifest_label "$app" "$key")  $(manifest_help_url "$app" "$key")"
        continue ;;
      *) continue ;;
    esac

    if dry; then
      echo "   ${c_yellow}dry-run${c_off} would generate $key ($kind)"
    else
      secrets_set ".apps.\"$app\".env.\"$key\"" "$new"
      ok "generated $key ($kind)"
    fi
    GENERATED=$((GENERATED + 1))
  done < <(manifest_key_names "$app")

}

# The paired half, as a second pass over everything.
#
# Amber's AMBER_MCP_PEER_TOKEN has to equal the token inside Bloom's BLOOM_MCP_KEYS
# ("amber:<token>") — two values that must match exactly, where a mismatch is a 401 on
# every delegated task and nothing anywhere says why.
#
# It is a separate pass because ordering decides correctness: filling amber before
# bloom exists means her peer token is copied from a placeholder, and any per-app
# ordering is the wrong one for somebody. Running this only after every app has its
# own keys makes the result independent of the order they were declared in.
pair_peers() {  # pair_peers APP...
  local app key peer peer_key mine theirs
  for app in "$@"; do
    manifest_have "$app" || continue
    while IFS= read -r key; do
      [ -z "$key" ] && continue
      peer="$(manifest_peer_of "$app" "$key")"
      peer_key="$(manifest_peer_key "$app" "$key")"
      if [ -z "$peer" ] || [ -z "$peer_key" ]; then continue; fi

      theirs="$(yq -r ".apps.\"$peer\".env.\"$peer_key\" // \"\"" "$SECRETS_FILE")"
      case "$theirs" in
        ''|null|*CHANGEME*)
          warn "$app.$key has nothing to match yet — declare and fill '$peer' first, then re-run this"
          continue ;;
      esac
      # "amber:<token>" -> "<token>": the label half says who is calling, and is not
      # the secret. Take the first entry if the peer accepts several.
      theirs="${theirs%%,*}"; theirs="${theirs##*:}"

      mine="$(yq -r ".apps.\"$app\".env.\"$key\" // \"\"" "$SECRETS_FILE")"
      [ "$mine" = "$theirs" ] && continue
      if dry; then
        echo "   ${c_yellow}dry-run${c_off} would copy $peer's $peer_key token into $app.$key"
      else
        secrets_set ".apps.\"$app\".env.\"$key\"" "$theirs"
        ok "$app.$key now matches $peer's $peer_key"
      fi
      GENERATED=$((GENERATED + 1))
    done < <(manifest_names_of_kind "$app" '^peer_token$')
  done
}

# The sync-store's own bearer list is not an app and has no manifest, so it keeps the
# placeholder rule: a CHANGEME under sync_store.keys[].token is a token nobody chose.
fill_sync_store() {
  local i n token
  n="$(yq -r '.sync_store.keys | length' "$SECRETS_FILE" 2>/dev/null || echo 0)"
  [ "$n" = "null" ] && n=0
  i=0
  while [ "$i" -lt "$n" ]; do
    token="$(yq -r ".sync_store.keys[$i].token // \"\"" "$SECRETS_FILE")"
    case "$token" in
      *CHANGEME*)
        if dry; then
          echo "   ${c_yellow}dry-run${c_off} would generate sync_store.keys[$i].token"
        else
          secrets_set ".sync_store.keys[$i].token" "$(gen_token)"
          ok "generated sync_store.keys[$i].token ($(yq -r ".sync_store.keys[$i].name" "$SECRETS_FILE"))"
        fi
        GENERATED=$((GENERATED + 1)) ;;
    esac
    i=$((i + 1))
  done
}

if [ -n "$APP" ]; then
  fill_app "$APP"
  # Still worth attempting: the peer this app points at may already be filled, in
  # which case there is a value to copy right now.
  pair_peers "$APP"
else
  step "Filling every declared app"
  fill_sync_store
  APPS=()
  while IFS= read -r app; do
    [ -z "$app" ] && continue
    APPS+=("$app")
    fill_app "$app"
  done < <(yq -r '.apps // {} | keys | .[]' "$SECRETS_FILE" 2>/dev/null || true)
  [ "${#APPS[@]}" -eq 0 ] || pair_peers "${APPS[@]}"
fi

echo
if dry; then
  ok "would generate $GENERATED value(s); nothing was written"
else
  ok "generated $GENERATED value(s)"
fi
if [ -n "$NEEDS" ]; then
  warn "still needs a value only you have:$NEEDS"
else
  ok "nothing left that this cannot generate"
fi
echo "     A generated *_KEYS token is only the ACCEPTING half — whatever presents it"
echo "     (a peer agent via the sync-store, or Aperture) needs the same value."
